### ISSUE TITLE
ts-node 报错

### ISSUE THREAD

**Issue by bqsgwys** [YunYouJun/mirai-ts#22]
``` shell
node_modules/mirai-ts/dist/index.js:5
import Mirai from "./mirai";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1024:16)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/lighthouse/mirai/bot/src/index.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module.m._compile (/home/lighthouse/mirai/bot/node_modules/ts-node/src/index.ts:1056:23)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by bqsgwys** [comment]
补充node直接执行报错：
``` nodejs
> const Mirai = require("mirai-ts");
/home/lighthouse/mirai/bot/node_modules/mirai-ts/dist/index.js:5
import Mirai from "./mirai";
^^^^^^

Uncaught:
SyntaxError: Cannot use import statement inside the Node.js REPL, alternatively use dynamic import
```

**Comment by bqsgwys** [comment]
版本如下：
```
info Direct dependencies
└─ mirai-ts@0.9.2
info All dependencies
├─ ansi-styles@4.3.0
├─ asynckit@0.4.0
├─ axios@0.21.1
├─ chalk@4.1.0
├─ color-convert@2.0.1
├─ color-name@1.1.4
├─ combined-stream@1.0.8
├─ delayed-stream@1.0.0
├─ follow-redirects@1.13.1
├─ form-data@3.0.0
├─ has-flag@4.0.0
├─ mime-db@1.45.0
├─ mime-types@2.1.28
├─ mirai-ts@0.9.2
├─ supports-color@7.2.0
└─ ws@7.4.2
```

**Comment by YunYouJun** [comment]
此部分由于 `0.9` 相比 `0.8` 提高了目标构建的 ES 版本所致。

node 可以通过为 package.json 添加 `type: 'module'` 字段，以体验新 `import` 的模块导入方式。

因为自己一直使用的新特性，所以没注意到这个问题。之后 mirai-ts 将会降低 ES 版本以兼容。
也可以先切换回 `0.8.x` 版本。

**Comment by YunYouJun** [comment]
Fixed in `0.9.3`.
